development:
  local:
    archive_dir: /Users/slatern/temp/archive
    cover_art_dir: /Users/slatern/temp/cover_art
    sample_media_files_dir: /Users/slatern/Music/m4a
    rar_path: /usr/local/bin/rar
  aws:
    region: us-west-2
  s3:
    bucket: nslater-media-pipeline-dev
    archive_prefix: archive/
    transcode_input_prefix: input/
    transcode_output_prefix: output/
    cover_art_prefix: cover_art/
    concurrent_uploads: 2
  db:
    file_table: media_file_dev
    archive_table: media_archive_dev
    title_table: media_title_dev
  cfn:
    stack_name: MediaPipelineDev
  sqs:
    transcode_queue: transcode_dev
    id3tag_queue: id3tag_dev
    cloudplayer_upload_queue: cloudplayer_dev
production:
  local:
    archive_dir: /Users/slatern/temp/archive
    cover_art_dir: /Users/slatern/temp/cover_art
    sample_media_files_dir: /Users/slatern/Music/m4a
    rar_path: /usr/local/bin/rar
  aws:
    region: us-west-2
  s3:
    bucket: nslater-media-pipeline
    archive_prefix: archive/
    transcode_input_prefix: input/
    transcode_output_prefix: output/
    cover_art_prefix: cover_art/
    concurrent_uploads: 2
  db:
    file_table: media_file
    archive_table: media_archive
    title_table: media_title
  cfn:
    stack_name: MediaPipeline
  sqs:
    transcode_queue: transcode
    id3tag_queue: id3tag
    cloudplayer_upload_queue: cloudplayer
