pipeline_name:
  local:
    archive_dir: /tmp/mediapipeline/archive
    download_dir: /tmp/mediapipeline/download
    cover_art_dir: /tmp/mediapipeline/cover_art
    rar_path: /usr/bin/rar
  aws:
    region: aws-region
  autoscale:
    transcode_queue_length: 2
  s3:
    bucket: s3_bucket_name
    archive_prefix: archive/
    transcode_input_prefix: input/
    transcode_output_prefix: output/
    cover_art_prefix: cover_art/
    tagged_output_prefix: tagged/
    concurrent_connections: 2
  db:
    file_table: media_file_table_name
    archive_table: media_archive_table_name
    stats_table: media_processing_stats_table_name
  sqs:
    transcode_queue: transcode_queue_name
    id3tag_queue: id3tag_queue_name
  transcoder:
    preset_id: 1351620000001-300010
    output_file_ext: mp3
  sns:
    transcode_topic_name: transcoder_topic_name
  schedule:
    hours_in_day: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
