local:
  archive_dir: /Users/nslater/archive
  cover_art_dir: /Users/nslater/cover_art
aws:
  region: us-west-2
s3:
  bucket: nslater-media-pipeline
  archive_prefix: archive/
  transcode_input_prefix: input/
  transcode_output_prefix: output/
  album_art_prefx: album_art/
db:
  file_table: media_file
  archive_table: media_archive
  title_table: media_title
