local:
  archive_dir: /Users/nslater/temp/archive
  cover_art_dir: /Users/nslater/temp/cover_art
  sample_media_files_dir: /Users/nslater/src/ruby/MediaPipeline/media_files
aws:
  region: us-west-2
s3:
  bucket: nslater-media-pipeline
  archive_prefix: archive/
  transcode_input_prefix: input/
  transcode_output_prefix: output/
  cover_art_prefix: cover_art/
db:
  file_table: media_file
  archive_table: media_archive
  title_table: media_title
